// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/proto/helloworld.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_641cff7980a2aacd, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_641cff7980a2aacd, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 請求數據 Request格式定義
type BidStreamRequest struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidStreamRequest) Reset()         { *m = BidStreamRequest{} }
func (m *BidStreamRequest) String() string { return proto.CompactTextString(m) }
func (*BidStreamRequest) ProtoMessage()    {}
func (*BidStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_641cff7980a2aacd, []int{2}
}

func (m *BidStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidStreamRequest.Unmarshal(m, b)
}
func (m *BidStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidStreamRequest.Marshal(b, m, deterministic)
}
func (m *BidStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidStreamRequest.Merge(m, src)
}
func (m *BidStreamRequest) XXX_Size() int {
	return xxx_messageInfo_BidStreamRequest.Size(m)
}
func (m *BidStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BidStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BidStreamRequest proto.InternalMessageInfo

func (m *BidStreamRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

// 響應數據Response格式定義
type BidStreamReply struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidStreamReply) Reset()         { *m = BidStreamReply{} }
func (m *BidStreamReply) String() string { return proto.CompactTextString(m) }
func (*BidStreamReply) ProtoMessage()    {}
func (*BidStreamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_641cff7980a2aacd, []int{3}
}

func (m *BidStreamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidStreamReply.Unmarshal(m, b)
}
func (m *BidStreamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidStreamReply.Marshal(b, m, deterministic)
}
func (m *BidStreamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidStreamReply.Merge(m, src)
}
func (m *BidStreamReply) XXX_Size() int {
	return xxx_messageInfo_BidStreamReply.Size(m)
}
func (m *BidStreamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BidStreamReply.DiscardUnknown(m)
}

var xxx_messageInfo_BidStreamReply proto.InternalMessageInfo

func (m *BidStreamReply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "proto.HelloReply")
	proto.RegisterType((*BidStreamRequest)(nil), "proto.BidStreamRequest")
	proto.RegisterType((*BidStreamReply)(nil), "proto.BidStreamReply")
}

func init() { proto.RegisterFile("helloworld/proto/helloworld.proto", fileDescriptor_641cff7980a2aacd) }

var fileDescriptor_641cff7980a2aacd = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x4d, 0x4f, 0x84, 0x30,
	0x10, 0x86, 0x83, 0xd9, 0x0f, 0x19, 0x8d, 0xd1, 0xfa, 0x45, 0xb8, 0xb8, 0x72, 0x30, 0x9c, 0xc0,
	0xe0, 0xc5, 0x8b, 0x31, 0xba, 0x87, 0xf5, 0xcc, 0x7a, 0xf4, 0xd2, 0x0d, 0x23, 0x4b, 0x52, 0xb6,
	0xb5, 0x0c, 0x31, 0xfc, 0x7b, 0xb3, 0x2d, 0x95, 0xd5, 0x3d, 0xc1, 0xbc, 0xf3, 0xf4, 0xe9, 0x5b,
	0xb8, 0x5d, 0xa3, 0x10, 0xf2, 0x5b, 0x6a, 0x51, 0xa4, 0x4a, 0x4b, 0x92, 0xe9, 0x10, 0x24, 0x26,
	0x60, 0x63, 0xf3, 0x09, 0x6f, 0x4a, 0x29, 0x4b, 0x81, 0x96, 0x5a, 0xb5, 0x9f, 0x29, 0x55, 0x35,
	0x36, 0xc4, 0x6b, 0x65, 0xb9, 0xe8, 0x03, 0x8e, 0xdf, 0xb6, 0x67, 0x73, 0xfc, 0x6a, 0xb1, 0x21,
	0xc6, 0x60, 0xb4, 0xe1, 0x35, 0x06, 0xde, 0xcc, 0x8b, 0xfd, 0xdc, 0xfc, 0xb3, 0x47, 0xf0, 0xe7,
	0x1a, 0x39, 0x61, 0xf1, 0x42, 0xc1, 0xc1, 0xcc, 0x8b, 0x8f, 0xb2, 0x30, 0xb1, 0xe2, 0xc4, 0x89,
	0x93, 0x77, 0x27, 0xce, 0x07, 0x38, 0xba, 0x03, 0xe8, 0xed, 0x4a, 0x74, 0x2c, 0x80, 0x69, 0x8d,
	0x4d, 0xc3, 0x4b, 0xa7, 0x77, 0x63, 0x14, 0xc3, 0xe9, 0x6b, 0x55, 0x2c, 0x49, 0x23, 0xaf, 0x5d,
	0x93, 0x0b, 0x18, 0x57, 0x1b, 0xd5, 0x52, 0xcf, 0xda, 0x21, 0x8a, 0xe1, 0x64, 0x87, 0xdc, 0x5a,
	0xaf, 0x60, 0x22, 0x5b, 0x1a, 0xc0, 0x7e, 0xca, 0x9e, 0x60, 0xba, 0xd0, 0x88, 0x84, 0x9a, 0x65,
	0x70, 0xb8, 0xe4, 0x9d, 0x69, 0xc2, 0xce, 0x6d, 0xe5, 0x64, 0xf7, 0xd5, 0xe1, 0xd9, 0xdf, 0x50,
	0x89, 0x2e, 0x5b, 0xc0, 0x68, 0xbe, 0xe6, 0xc4, 0x9e, 0xc1, 0xff, 0xbd, 0x90, 0x5d, 0xf7, 0xdc,
	0xff, 0xb2, 0xe1, 0xe5, 0xfe, 0x42, 0x89, 0x2e, 0xf6, 0xee, 0xbd, 0xd5, 0xc4, 0x6c, 0x1e, 0x7e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x08, 0x96, 0x20, 0xe3, 0xb5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/proto/helloworld.proto",
}

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	BidStream(ctx context.Context, opts ...grpc.CallOption) (Chat_BidStreamClient, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) BidStream(ctx context.Context, opts ...grpc.CallOption) (Chat_BidStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/proto.Chat/BidStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatBidStreamClient{stream}
	return x, nil
}

type Chat_BidStreamClient interface {
	Send(*BidStreamRequest) error
	Recv() (*BidStreamReply, error)
	grpc.ClientStream
}

type chatBidStreamClient struct {
	grpc.ClientStream
}

func (x *chatBidStreamClient) Send(m *BidStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatBidStreamClient) Recv() (*BidStreamReply, error) {
	m := new(BidStreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	BidStream(Chat_BidStreamServer) error
}

// UnimplementedChatServer can be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (*UnimplementedChatServer) BidStream(srv Chat_BidStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BidStream not implemented")
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_BidStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).BidStream(&chatBidStreamServer{stream})
}

type Chat_BidStreamServer interface {
	Send(*BidStreamReply) error
	Recv() (*BidStreamRequest, error)
	grpc.ServerStream
}

type chatBidStreamServer struct {
	grpc.ServerStream
}

func (x *chatBidStreamServer) Send(m *BidStreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatBidStreamServer) Recv() (*BidStreamRequest, error) {
	m := new(BidStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidStream",
			Handler:       _Chat_BidStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld/proto/helloworld.proto",
}
